apps/noobscribe/webs/shop/urls.py
from django.urls import path
from .views import (
    ProductIndexView,
    CartView,
    CheckoutView,
    cart_add_product,
    cart_remove_product
)

urlpatterns = [
    path('', ProductIndexView.as_view(), name='shop_index'),
    path('checkout/', CheckoutView.as_view(), name='cart_checkout'),
    path('cart/', CartView.as_view(), name='cart_index'),
    path('cart/add/', cart_add_product, name='cart_add_product'),
    path('cart/delete/', cart_remove_product, name='cart_remove_product')
    
]

apps/noobsite/urls.py
"""
    Noobsite URL Configuration
"""

from django.conf import settings
from django.urls import path, include
from noobscribe.webs import urls as web_urls
from noobscribe.api import urls as api_urls

urlpatterns = [
    path('api/', include(api_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.contrib import admin
    
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path('admin/', admin.site.urls),
        path('admin/queues/', include('django_rq.urls'))
    ]

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    path('', include(web_urls)),
]

apps/noobscribe/plans/models.py
import uuid
import enum
from django.db import models
from django.utils.translation import ugettext_lazy as _
from polymorphic.models import PolymorphicModel, PolymorphicManager
from noobscribe.auth.models import MemberLevel


class BalanceType(enum.Enum):
    FAN = 'FANS'
    FOLLOWER = 'FOLL'
    SUBSCRIBER = 'SUBS'
    COMMENT = 'COMM'
    LIKE = 'LIKE'
    DISLIKE = 'DISL'
    VIEW = 'VIEW'

    CHOICES = (
        (FAN, _('Fan')),
        (FOLLOWER, _('Follower')),
        (SUBSCRIBER, _('Subscriber')),
        (COMMENT, _('Comment')),
        (LIKE, _('Like')),
        (DISLIKE, _('Dislike')),
        (VIEW, _('View')),
    )


class PlatformType(enum.Enum):
    YOUTUBE = 'YT'
    FACEBOOK = 'FB'
    INSTAGRAM = 'IG'
    SOUNDCLOUD = 'SC'

    CHOICES = (
        (YOUTUBE, _('Youtube')),
        (FACEBOOK, _('Facebook')),
        (INSTAGRAM, _('Instagram')),
        (SOUNDCLOUD, _('SoundCloud')),
    )


class ProductManager(PolymorphicManager):

    def get_queryset(self):
        return super().get_queryset().non_polymorphic()


class Product(PolymorphicModel):
    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('product')

    id = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        primary_key=True,
        verbose_name='uuid'
    )
    name = models.CharField(max_length=54, verbose_name=_('name'))
    unit_of_measure = models.CharField(
        max_length=25, null=True, blank=False,
        verbose_name=_('unit')
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name=_('price'),
        help_text=_('price per month')
    )

    def __str__(self):
        return self.name


class Membership(Product):
    class Meta:
        verbose_name = _('Member')
        verbose_name_plural = _('Member')

    member_level = models.ForeignKey(
        MemberLevel, on_delete=models.CASCADE,
        null=True, blank=False, # Todo Must not null 
        related_name='products',
        verbose_name=_('member level')
        )
    validity = models.PositiveIntegerField(
        verbose_name=_('validity'),
        help_text=_('validity')
        )

    def __str__(self):
        return self.name


class Quota(Product):
    class Meta:
        verbose_name = _('Quota')
        verbose_name_plural = _('Quota')

    platform = models.CharField(
        max_length=4,
        choices=PlatformType.CHOICES.value,
        default=PlatformType.YOUTUBE.value,
        verbose_name=_('platform')
    )
    balance_type = models.CharField(
        max_length=4,
        choices=BalanceType.CHOICES.value,
        default=BalanceType.SUBSCRIBER.value,
        verbose_name=_('balance type')
    )
    quantity = models.PositiveIntegerField(
        verbose_name=_('quantity'),
        help_text=_('quantity')
        )

    def __str__(self):
        return self.name

apps/noobscribe/webs/shop/forms.py
from django import forms
from django.contrib.auth import get_user_model
from noobscribe.plans.models import Product
from noobscribe.sales.models import SalesOrder, Cart


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ('owner', 'product', 'quantity')
    
    owner = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all()
    )
    product = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Product.objects.all()
    )
    quantity = forms.ChoiceField(
        widget=forms.Select,
        choices=[(x, x) for x in range(1, 11)],
    )


class CheckoutForm(forms.ModelForm):

    class Meta:
        model = SalesOrder
        fields = ('promo_code', 'note')

apps/noobscribe/webs/shop/views.py
from django.db import transaction, models
from django.views.generic import ListView, FormView
from django.shortcuts import get_object_or_404, HttpResponseRedirect, HttpResponse, reverse
from noobscribe.plans.models import Quota, Product
from noobscribe.sales.models import Cart, SalesOrder, OrderItem

from .forms import CheckoutForm, CartForm


class ProductIndexView(ListView):
    """ Quota Index View """
    model = Quota
    template_name = 'shop/product_list.html'


class CartView(ListView):
    model = Cart
    template_name = 'shop/cart_list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)


def cart_add_product(request):
    if request.method != 'POST':
        return Http404
    product_id=request.POST.get('product')
    product = get_object_or_404(Product, pk=product_id)
    item = Cart.objects.add_product(request, product)
    return HttpResponseRedirect(reverse('cart_index'))
    

def cart_remove_product(request):
    if request.method != 'POST':
        return Http404
    item_id=request.POST.get('item')
    item = get_object_or_404(Cart, pk=item_id)
    item.delete()
    return HttpResponseRedirect(reverse('cart_index'))


class CheckoutView(FormView):
    form_class = CheckoutForm
    template_name = 'shop/checkout_view.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        items = Cart.objects.user_cart(self.request)
        total = items.aggregate(price=models.Sum('product__price'))
        context.update({
            'object_list': items,
            'total': total['price']
        })
        return context

    def get_success_url(self):
        return reverse('shop_index')

    def form_valid(self, form):
        with transaction.atomic():
            items = Cart.objects.user_cart(self.request)
            order = SalesOrder(owner=self.request.user)
            order.save()
            for item in items:
                order_item = OrderItem(order=order, product=item.product)
                order_item.save()
            items.delete()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        return self.render_to_response(self.get_context_data(form=form))

apps/noobscribe/webs/templates/shop/cart_list.html
{% extends 'base.html' %}

{% block content %}

<div>
{% if object_list.count == 0 %}
    <h1>Cart is empty</h1>
    <a href="{% url 'shop_index' %}">Select Product</a>
{% else %}
    {% for item in object_list %}
        <h1>{{ item.product }}</h1>
        <ul>
            <li>Quantity: {{ item.quantity }}</li>
            <li>Price: {{ item.product.price }} </li>
        </ul>
        <form action="{% url 'cart_remove_product' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="item" value="{{ item.id }}">
            <input type="submit" value="Remove">
        </form>
    {% endfor %}
    <div>
        <a href="{% url 'shop_index' %}">Continue Shopping</a>
        <a href="{% url 'cart_checkout' %}">Check Out</a>
    </div>
{% endif %}
</div>
{% endblock %}

apps/noobscribe/webs/templates/shop/checkout_view.html
{% extends 'base.html' %}

{% block content %}
<div>
    {% if object_list.count == 0 %}
        <h1>Cart is empty</h1>
        <a href="{% url 'shop_index' %}">Select Product</a>
    {% else %}
        {% for item in object_list %}
            <h1>{{ item.product }}</h1>
            <ul>
                <li>Quantity: {{ item.quantity }}</li>
                <li>Price: {{ item.product.price }} </li>
            </ul>
        {% endfor %}
        <h3>Total: {{ total }}</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Complete Checkout">
            <input type="button" value="Cancel" onclick="javascript:location.href='{% url 'cart_index' %}'">
        </form>
    {% endif %}
</div>
{% endblock %}

apps/noobscribe/webs/templates/shop/product_list.html
{% extends 'base.html' %}

{% block content %}

{% for product in object_list %}
    <div>
        <h1>{{ product.name }}</h1>
        <ul>
            <li>{{ product.get_platform_display }}</li>
            <li>{{ product.get_balance_type_display }}</li>
            <li>Price: {{ product.price }} </li>
        </ul>
        <form action="{% url 'cart_add_product' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="product" value="{{ product.id }}">
            <input type="submit" value="Add To Cart">
        </form>
    </div>
{% endfor %}

{% endblock %}